version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    registries:
      - "github-packages"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    allow:
      - dependency-name: "org.example:repo1-lib"


registries:
  github-packages:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/GC-test-dep"
    username: "${{secrets.DEPENDABOT_USERNAME}}"
    password: "${{secrets.DEPENDABOT_TOKEN}}"
