version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    registries:
      - "github-packages"
    open-pull-requests-limit: 5
    # optional: labels you want Dependabot to add
    labels:
      - "dependencies"
      - "dependabot"
    # example ignore rule (optional)
    ignore:
      - dependency-name: "com.example:repo1-lib"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

registries:
  github-packages:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/GC-test-dep"
    # token must reference a Dependabot secret (created in the Dependabot secrets section)
    token: "${{secrets.DEPENDABOT_TOKEN}}"