name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p $GITHUB_WORKSPACE/.github
          cat > $GITHUB_WORKSPACE/settings.xml <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" ...>
            <servers>
              <server>
                <id>github</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          XML
      - name: Build with Maven
        run: mvn -B -U -s $GITHUB_WORKSPACE/settings.xml clean package